"""clean_redundant_indexes

Revision ID: bd64cf275c37
Revises: 0003
Create Date: 2026-06-28 02:58:58.748513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd64cf275c37'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insumos_codigo_barras'), table_name='insumos')
    op.drop_index(op.f('ix_insumos_sku'), table_name='insumos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_insumos_sku'), 'insumos', ['sku'], unique=True)
    op.create_index(op.f('ix_insumos_codigo_barras'), 'insumos', ['codigo_barras'], unique=True)
    # ### end Alembic commands ###
